import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';
import './stars.css';
import './admin.css';

const api = import.meta.env.VITE_API_URL || 'http://localhost:5000/api';
const defaultCover = 'https://images.unsplash.com/photo-1497250681960-ef046c08a56e?auto=format&fit=crop&w=1000&q=85';
const blankPage = () => ({ topText: '', leftText: '', rightImage: '', leftImage: '', rightText: '', bottomText: '' });
const demo = { _id: 'welcome', title: 'A place for dreams', subtitle: 'Made of words, light, and the moments between.', coverImage: defaultCover, author: { username: 'papermoon' }, pages: [{ topText: 'Welcome to PaperMoon', leftText: 'Every dream deserves room to breathe. Build yours page by page, in your own rhythm.', rightImage: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1000&q=80', leftImage: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1000&q=80', rightText: 'Write a small beginning, then let your photographs hold the details words cannot.', bottomText: 'This is your little corner of the moon.' }] };

function App() {
 const [user,setUser]=useState(()=>JSON.parse(localStorage.getItem('pm-user')||'null')); const [token,setToken]=useState(()=>localStorage.getItem('pm-token')); const [stories,setStories]=useState([demo]); const [story,setStory]=useState(demo); const [screen,setScreen]=useState('home'); const [edit,setEdit]=useState(false); const [pageIndex,setPageIndex]=useState(0); const [pageLoading,setPageLoading]=useState(false); const [authOpen,setAuthOpen]=useState(false); const [authMode,setAuthMode]=useState('login'); const [form,setForm]=useState({username:'',password:''}); const [error,setError]=useState('');
 const own=user&&(story.author?._id===user.id||story.author?.username===user.username); const admin=user?.username==='vikasn'; const cover=story.coverImage||defaultCover;
 useEffect(()=>{fetch(`${api}/dreams`).then(r=>r.ok?r.json():[]).then(x=>x.length&&setStories(x)).catch(()=>{})},[]);
 const call=async(path,options={})=>{const r=await fetch(api+path,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})}});const data=r.status===204?null:await r.json();if(!r.ok)throw new Error(data?.message);return data};
 const authenticate=async e=>{e.preventDefault();setError('');try{const data=await call(`/auth/${authMode==='login'?'login':'register'}`,{method:'POST',body:JSON.stringify(form)});setUser(data.user);setToken(data.token);localStorage.setItem('pm-user',JSON.stringify(data.user));localStorage.setItem('pm-token',data.token);setAuthOpen(false)}catch(e){setError(e.message)}};
 const refreshStories=async()=>{try{const r=await fetch(`${api}/dreams`);const all=await r.json();if(all.length)setStories(all)}catch{}};
 const openStory=async s=>{window.scrollTo({top:0,left:0,behavior:'smooth'});setStory(s);setPageIndex(0);setEdit(false);setScreen('story');if(s._id==='welcome')return;try{const r=await fetch(`${api}/dreams/${s._id}`);if(r.ok){const fresh=await r.json();setStory(fresh);setStories(list=>list.map(x=>x._id===fresh._id?fresh:x))}}catch{}};
 const create=async()=>{if(!user){setAuthOpen(true);return}const s={title:'Untitled dream',subtitle:'',coverImage:'',pages:[blankPage()]};try{const data=await call('/dreams',{method:'POST',body:JSON.stringify(s)});data.author={_id:user.id,username:user.username};setStories([data,...stories]);setStory(data)}catch{const local={...s,_id:'local-'+Date.now(),author:{_id:user.id,username:user.username}};setStories([local,...stories]);setStory(local)}setEdit(true);setPageIndex(0);setScreen('story')};
 const save=async()=>{if(story._id.startsWith('local-'))return;try{const fresh=await call(`/dreams/${story._id}`,{method:'PUT',body:JSON.stringify({title:story.title,subtitle:story.subtitle,coverImage:story.coverImage,pages:story.pages})});setStory(fresh);setStories(list=>list.map(x=>x._id===fresh._id?fresh:x));await refreshStories()}catch(e){alert(e.message)}};
 const openAdmin=async()=>{await refreshStories();setScreen('admin');window.scrollTo({top:0,behavior:'smooth'})}; const deleteDream=async id=>{if(!window.confirm('Delete this dream permanently?'))return;try{await call(`/dreams/${id}`,{method:'DELETE'});setStories(list=>list.filter(d=>d._id!==id))}catch(e){alert(e.message)}};
 const update=(key,value)=>setStory(s=>({...s,pages:s.pages.map((p,i)=>i===pageIndex?{...p,[key]:value}:p)}));
 const upload=async(file,setter)=>{if(!file)return;const preview=URL.createObjectURL(file);setter(preview);if(token){try{const fd=new FormData();fd.append('image',file);const r=await fetch(`${api}/upload`,{method:'POST',headers:{Authorization:`Bearer ${token}`},body:fd});if(r.ok)setter((await r.json()).url)}catch{}}};
 const turnPage=next=>{if(next===pageIndex||next<0||next>=story.pages.length)return;setPageLoading(true);setTimeout(()=>{setPageIndex(next);setPageLoading(false);window.scrollTo({top:0,left:0,behavior:'smooth'})},800)}; const p=story.pages[pageIndex]||blankPage();
 return <><div className="star-field"/>{pageLoading&&<div className="page-loader" aria-label="Turning the page"><span className="loader-moon"/><p>turning the page</p></div>}<header><button className="brand" onClick={()=>{window.scrollTo({top:0,behavior:'smooth'});setScreen('home')}} aria-label="PaperMoon home"><span className="moon"/><span>paper</span><b>moon</b></button><nav>{admin&&<button className="admin" onClick={openAdmin}>Admin</button>}<button className="new" onClick={create}>Write a dream</button>{user?<button className="account" onClick={()=>{localStorage.clear();setUser(null);setToken(null)}}>@{user.username} · sign out</button>:<button className="account" onClick={()=>setAuthOpen(true)}>Sign in</button>}</nav></header>
 {screen==='home'?<Home stories={stories} onOpen={openStory} onCreate={create}/>:screen==='admin'?<Admin dreams={stories} onBack={()=>{window.scrollTo({top:0,behavior:'smooth'});setScreen('home')}} onDelete={deleteDream}/>:<main className="reader"><button className="back" onClick={()=>{window.scrollTo({top:0,behavior:'smooth'});setScreen('home')}}>← All dreams</button><div className="story-head"><div><p className="eyebrow">A PAPERMOON DREAM</p>{edit?<input value={story.title} onChange={e=>setStory({...story,title:e.target.value})}/>:<h1>{story.title}</h1>}{edit?<input className="subtitle-input" value={story.subtitle} placeholder="Add a subtitle" onChange={e=>setStory({...story,subtitle:e.target.value})}/>:<p className="subtitle">{story.subtitle}</p>}<p className="byline">Words and photographs by <b>{story.author?.username}</b></p></div>{own&&<button className="edit-btn" onClick={()=>{if(edit)save();setEdit(!edit)}}>{edit?'Save dream':'Edit dream'}</button>}</div>
 <div className="cover" style={{backgroundImage:`url(${cover})`}}>{edit&&pageIndex===0&&<label><input type="file" accept="image/*" onChange={e=>upload(e.target.files[0],v=>setStory({...story,coverImage:v}))}/><span>{story.coverImage?'Change cover photo':'Add a cover photo'}</span></label>}<div><p>PaperMoon dream</p><strong>{story.title}</strong></div></div>
 <article className="paper"><Text text={p.topText} edit={edit} onChange={v=>update('topText',v)} cls="d1"/><div className="d2"><Text text={p.leftText} edit={edit} onChange={v=>update('leftText',v)} cls="d21"/><Image src={p.rightImage} edit={edit} onFile={f=>upload(f,v=>update('rightImage',v))} cls="d22"/></div><div className="d3"><Image src={p.leftImage} edit={edit} onFile={f=>upload(f,v=>update('leftImage',v))} cls="d31"/><Text text={p.rightText} edit={edit} onChange={v=>update('rightText',v)} cls="d32"/></div><Text text={p.bottomText} edit={edit} onChange={v=>update('bottomText',v)} cls="d4"/></article>
 <footer><button disabled={pageIndex===0||pageLoading} onClick={()=>turnPage(pageIndex-1)}>← Previous</button><span>Page {pageIndex+1} of {story.pages.length}</span><button disabled={pageIndex===story.pages.length-1||pageLoading} onClick={()=>turnPage(pageIndex+1)}>Next →</button>{edit&&<button className="add" onClick={()=>{setStory({...story,pages:[...story.pages,blankPage()]});setPageIndex(story.pages.length)}}>＋ Add page</button>}</footer></main>}
 {authOpen&&<Auth form={form} setForm={setForm} mode={authMode} setMode={setAuthMode} error={error} close={()=>setAuthOpen(false)} submit={authenticate}/>}</>}
function Home({stories,onOpen,onCreate}){return <main className="home"><section className="hero"><p className="eyebrow">DREAMS, PAGE BY PAGE</p><h1>A quieter place for <em>your</em> dreams.</h1><p>PaperMoon lets you create visual dreams with words and photographs, arranged like a small printed journal.</p><button className="hero-button" onClick={onCreate}>Start dreaming <span>→</span></button></section><section className="library"><div className="library-head"><p className="eyebrow">EXPLORE THE DREAMS</p><p>{stories.length} dreams waiting to be opened</p></div><div className="card-grid">{stories.map((s,i)=><button className="story-card" style={{'--delay':`${i*80}ms`}} key={s._id} onClick={()=>onOpen(s)}><img src={s.coverImage||defaultCover} alt=""/><span className="card-shade"/><div><small>BY {s.author?.username}</small><strong>{s.title}</strong><em>{s.subtitle||'A dream in the making'}</em></div></button>)}</div></section></main>}
function Admin({dreams,onBack,onDelete}){return <main className="admin-page"><button className="back" onClick={onBack}>← Back to dreams</button><p className="eyebrow">ADMINISTRATION</p><h1>Manage dreams</h1><p className="admin-intro">{dreams.length} published dreams</p><div className="dream-list">{dreams.map(d=><div className="dream-row" key={d._id}><div><strong>{d.title||'Untitled dream'}</strong><small>by {d.author?.username||'unknown'}</small></div><button className="delete" onClick={()=>onDelete(d._id)} aria-label={`Delete ${d.title}`}>⌫ <span>Delete</span></button></div>)}</div></main>}
function Auth({form,setForm,mode,setMode,error,close,submit}){return <div className="modal"><form onSubmit={submit}><button type="button" className="close" onClick={close}>×</button><div className="auth-moon"/><p className="eyebrow">WELCOME TO PAPERMOON</p><h2>{mode==='login'?'Your dreams are waiting.':'Make room for your dreams.'}</h2><p className="auth-copy">{mode==='login'?'Sign in to write, edit, and return to your pages.':'A simple account is all you need to begin.'}</p><input placeholder="Choose a username" required value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/><input placeholder="Create a password" type="password" required value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/>{error&&<small className="error">{error}</small>}<button className="submit">{mode==='login'?'Sign in':'Create account'} <span>→</span></button><button type="button" className="switch" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'New here? Create an account':'Already have an account? Sign in'}</button></form></div>}
function Text({text,edit,onChange,cls}){return <div className={'text-block '+cls}>{edit?<textarea value={text} placeholder="Write here…" onChange={e=>onChange(e.target.value)}/>:<p>{text||' '}</p>}</div>};function Image({src,edit,onFile,cls}){return <div className={'image-block '+cls}>{src&&<img src={src} alt="Dream photograph"/>}{edit&&<label><input type="file" accept="image/*" onChange={e=>onFile(e.target.files[0])}/><span>{src?'Change photograph':'Upload photograph'}</span></label>}</div>};createRoot(document.getElementById('root')).render(<App/>);
